name: "go-blog"
mode: "dev"
port: 3939
version: "v0.1.1"
start_time: "2023-01-01"
machine_ID: 393939

# 日志配置
log:
  level: "debug"
  filename: "go-blog.log"
  max_size: 200
  max_age: 30
  max_backups: 7

# mysql配置
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "root"
  dbname: "go_blog"
  max_open_conns: 200
  max_idle_conns: 50

# redis配置
redis:
  host: "127.0.0.1"
  port: 6379
  password: "redis"
  db: 0
  pool_size: 100


